name: linux

on: [push, pull_request]

jobs:

  # Build all tutorials
  build_wave_eqn:
    name: GNU@7.5 C++14 [tutorials]
    runs-on: ubuntu-22.04
    env:
#      {CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wunreachable-code -fno-operator-names"}
      AMREX_HOME: ${{ github.workspace }}/amrex
    steps:
    - name: Checkout AMReX
      uses: actions/checkout@v4
      with:
       repository: AMReX-Codes/amrex
       path: ${{ github.workspace }}/amrex

    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
      with:
       path: ${{ github.workspace }}/amrex_wave_eqn

    - name: Dependencies
      run: ${{ github.workspace }}/amrex_wave_eqn/.github/workflows/dependencies/dependencies.sh

    - name: Build & Install
      run: |
          cd ${{ github.workspace }}/amrex_wave_eqn
          make -j 4 USE_CATALYST=FALSE USE_CONDUIT=FALSE

    - name: Run test case
      run: mpiexec -np 2 ./main3d.intel-llvm.MPI.ex ./inputs
      working-directory: ${{ github.workspace }}/amrex_wave_eqn