name: macos

on: [push, pull_request]

env:
  CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wextra-semi -Wunreachable-code -fno-operator-names"

jobs:
  # Build all tutorials
  tests-macos:
    name: AppleClang@14.0 GFortran@12.2 [tutorials]
    runs-on: macos-latest
    
    steps:
    - name: Checkout AMReX
      uses: actions/checkout@v4
      with:
       repository: AMReX-Codes/amrex
       path: ${{ github.workspace }}/amrex
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
      with:
       path: ${{ github.workspace }}/amrex_wave_eqn

    - name: Dependencies
      run: ${{ github.workspace }}/amrex_wave_eqn/.github/workflows/dependencies/dependencies_mac.sh
      
    - name: Build & Install
      run: |
       export LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/current
       cd ${{ github.workspace }}/amrex_wave_eqn
       make -j 4


