name: macos

on: [push, pull_request]

env:
  CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wextra-semi -Wunreachable-code -fno-operator-names"

jobs:
  # Build all tutorials
  tests-macos:
    name: AppleClang@14.0 GFortran@12.2 [tutorials]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_mac.sh
    - name: Build & Install
      run: |
        export LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/current

	make -j 4 

